### ISSUE TITLE
Method 'addMaterial' is not defined for class 'GLTF' or is removed from MATLAB's search path.

### ISSUE THREAD

**Issue by m-bob** [rohan-collins/MATLAB-GLTF#1]
Hi,

I'm really looking forward to using this well-structured and well-documented program. It looks far better than anything I've been able to find in Python.

Unfortunately, I can't get it to work for me.

When I try your first example, the following works fine:

V=[1 1 1;-1 -1 1;1 -1 -1;-1 1 -1];
F=[1 2 3;1 3 4;1 4 2;2 4 3];
C=[0 1 0]; % green
patch('Faces',F,'Vertices',V,'FaceColor',C);
axis equal tight;
view(3);

I see the green tetrahedron.

But the key statement fails:

GLTF(F,V,C).writeGLTF("test.gltf");

gives 
Error using GLTF/addMaterial
Method 'addMaterial' is not defined for class 'GLTF' or is removed from MATLAB's search path.

Error in GLTF (line 70)
               gltf.addNode('mesh',gltf.addMesh(V,'indices',F,'material',gltf.addMaterial('baseColorFactor',C)));

There is nothing obviously wrong with the file addMaterial.m, so I'm at a loss.

I'm using MATLAB R2020b Update 8 on an old MacBook Pro.

Any suggestions?

Thanks!

Murray

**Comment by m-bob** [comment]
I think I may have figured it out. I have never used MATLAB classes before and there's a required folder structure.

Your code must (I think) go in a folder named @GLTF . That folder does _not_ go in the MATLAB path. The folder @GLTF should be placed in another folder, say XFolder.  The folder XFolder should be added to the MATLAB path.

Sorta like:

XFolder (add to MATLAB path)
|_________@GLTF (not in MATLAB path)
                   |__________ GLTF.m
                                         and your remaining files

**Comment by rohan-collins** [comment]
Hi Murray,

Yes, that is correct. I have neglected to update installation instructions, I'll clarify it in the next update.

**Comment by rohan-collins** [comment]
The code base has been updated to be installable as an add-on via MATLAB now.
