### ISSUE TITLE
how to set the program folder and make the program work correctly？Thank you！

### ISSUE THREAD

**Issue by gascendcn** [rohan-collins/MATLAB-GLTF#14]
Hi
When I ran the sample program, I met the errors in Matlab as follows， how to solve them and make the program work correctly？ Thank you！

 errors in Matlab

>> sample_plot3
Error using GLTF/addMaterial
Method 'addMaterial' is not defined for class 'GLTF' or is removed from MATLAB's search path.

Error in sample_plot3 (line 48)
material_idx=gltf.addMaterial('baseColorFactor',C);
 
>> sample_scatter3
Unrecognized function or variable 'sphere3d'.

Error in sample_scatter3 (line 33)
[F,V]=sphere3d('Resolution',5);

**Comment by rohan-collins** [comment]
Clone the contents of this repository into a folder called @GLTF (yes, the "@" is essential). This folder can be anywhere inside another folder that is already on the MATLAB path, but the @GLTF folder itself should not be added to the path. The samples and functions folders inside the class folder cannot be added to path. The sample scripts and functions respectively in those folders can be accessed by running them from within the folder. Alternatively, you can copy those folders to somewhere outside the class folder and add them to the MATLAB path.

For more information, please refer to ["Using Class Folders"](https://mathworks.com/help/matlab/matlab_oop/organizing-classes-in-folders.html) in MATLAB documentation.

**Comment by rohan-collins** [comment]
The code base has been updated to be installable as an add-on via MATLAB now.
