### ISSUE TITLE
Help with transparent, texture glass object

### ISSUE THREAD

**Issue by m-bob** [rohan-collins/MATLAB-GLTF#2]
I'm trying to create a textured, transparent glass object. I've seen examples of creating a glass material such as

glass_material = Material.from_dict({
    "name": "glass_material",
    "pbrMetallicRoughness": {
        "baseColorTexture": {"index": 0},
        "metallicFactor": 0,
        "roughnessFactor": 0.5,
    },
    "alphaMode": "BLEND",
    "doubleSided": True,
})

but I haven't been able to replicate that using your library.

Can you provide an example of a textured, transparent glass object (box, sphere, etc?)

I've been trying to accomplish this without success so far. One problem, I think, is specifying alphaMode as BLEND. Somehow that may be achievable by specifying the baseColorFactor appropriately, but I don't know how to do that. 

I realize this request is for "going above and beyond" but so far your library is the best tool I've found: I've had much less luck using the Python libraries. Your documentation is better than theirs and your 'API' is more straightforward.

Thanks for any help you can provide!

**Comment by rohan-collins** [comment]
Hi Murray,
Good point. There wasn't much clarity on the behaviour of Alpha Mode on textured materials when I first wrote the code. I have added the ability to set Alpha Mode independently of Base Colour Factor, this should enable you to do what you want. In any case, you can always edit the GLTF object as a structure after creation.

**Comment by m-bob** [comment]
Thanks Rohan! I'll try it.
